In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
cols = ["area", "perimeter", "compactness", "length", "width", "asymmetry", "groove", "class"]
df = pd.read_csv('seeds/seeds_dataset.txt', names=cols, sep="\s+")

In [31]:
df.head()

area  perimeter  compactness  length  width  asymmetry  groove  class
0  15.26      14.84       0.8710   5.763  3.312      2.221   5.220      1
1  14.88      14.57       0.8811   5.554  3.333      1.018   4.956      1
2  14.29      14.09       0.9050   5.291  3.337      2.699   4.825      1
3  13.84      13.94       0.8955   5.324  3.379      2.259   4.805      1
4  16.14      14.99       0.9034   5.658  3.562      1.355   5.175      1

In [ ]:
for i in range(len(cols)-1):
    for j in range(i+1, len(cols)-1):
        x_label = cols[i]
        y_label = cols[j]
        sns.scatterplot(x=x_label, y=y_label, data=df, hue='class')
        plt.show()


K-Means Clustering

In [32]:
from sklearn.cluster import KMeans

In [59]:
x_col="compactness"
y_col="asymmetry"
x = df[[x_col,y_col]].values

In [60]:
kmeans = KMeans(n_clusters=3).fit(x)

In [61]:
clusters = kmeans.labels_

In [62]:
clusters

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 2, 0, 2, 2, 2, 0, 0, 0, 0, 1,
       2, 2, 0, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 0,
       1, 1, 2, 1, 1, 0, 0, 1, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 2, 1, 1,
       1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 0, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1,
       2, 1, 2, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1,
       1, 0, 2, 0, 1, 2, 1, 1, 1, 2, 1, 2], dtype=int32)

In [63]:
df['class'].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [64]:
cluster_df = pd.DataFrame(np.hstack((x, clusters.reshape(-1,1))), columns=[x_col,y_col,"class"])

In [ ]:
# K-Means classes
sns.scatterplot(x=x_col, y=y_col, hue='class', data = cluster_df)
plt.plot()

In [ ]:
# Original classes
sns.scatterplot(x=x_col, y=y_col, hue='class', data = df)
plt.plot()

Higher dimensions

In [67]:
X = df[cols[:-1]].values

In [71]:
kmeans = KMeans(n_clusters=3).fit(X)
cluster_df = pd.DataFrame(np.hstack((X, kmeans.labels_.reshape(-1,1))), columns=df.columns)

In [ ]:
# K-Means classes
sns.scatterplot(x=x_col, y=y_col, hue='class', data = cluster_df)
plt.plot()

In [ ]:
# Original classes
sns.scatterplot(x=x_col, y=y_col, hue='class', data = df)
plt.plot()

PCA

In [74]:
from sklearn.decomposition import PCA

In [75]:
pca = PCA(n_components=2)
transformed_x = pca.fit_transform(X)

In [76]:
X.shape

(210, 7)

In [77]:
transformed_x.shape

(210, 2)

In [78]:
transformed_x[:5]

array([[ 0.66344838, -1.41732098],
       [ 0.31566651, -2.68922915],
       [-0.6604993 , -1.13150635],
       [-1.0552759 , -1.62119002],
       [ 1.61999921, -2.18338442]])

In [ ]:
plt.scatter(transformed_x[:,0], transformed_x[:,1])
plt.show()

In [80]:
kmeans_pca_df = pd.DataFrame(np.hstack((transformed_x, kmeans.labels_.reshape(-1,1))), columns=["pca1", "pca2", "class"])

In [81]:
truth_pca_df = pd.DataFrame(np.hstack((transformed_x, df["class"].values.reshape(-1,1))), columns=["pca1", "pca2", "class"])

In [ ]:
# K-Means classes
sns.scatterplot(x="pca1", y="pca2", hue='class', data = kmeans_pca_df)
plt.plot()

In [ ]:
# Truth classes
sns.scatterplot(x="pca1", y="pca2", hue='class', data = truth_pca_df)
plt.plot()